### ISSUE TITLE
Feature ideas... URL encoding like Prof. Esperança does

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#143]
So, this could be a nice way of sharing stuff... [example from SkulptIDE](https://esperanc.github.io/skulptIde/?lzsrc=MQKGAIEkDsBcFMBOBDAxrAlgN3uA5ohgCbgAOysCi04A7hrABbiyHLR4A28AzmGOABCyHvBIB7GqUTiCyALbgACgDoATCoCMKgCzhxAM3AAiAOLxoSCtlwARXhjzRj4AEYBPAQAkVQ8Y2g0AGskABohX1MZHh5wgClfABlkAFdXcIBhJOQALxykSQx+EAMZRWlxVF4eDA5wDHlScURYcAAqErLweQpmBqaW8Ap2NVCUIgx2PhBMbgzxFLhwAF5wTQAGEBAieCNRWBTSAAoASgAuEHAr8Br8o4A2dfXQx-WTy+uDDE5OcCPnjZvD5XaDiADKrHEIVOwOuV22u3ARBQtAy8B+f3OsNYkw43D+zwBAIA7KEALQbUKaYnvBFGZHIWinC5w1zBAgLaBEI5qACsvPecKI7hW4AsWAwMmg8gssBUjHgjkYrQA9CxvvB5otYLCiAAPUXiyWSGVwFT0IhMcBq2aazk6uEGZr4QhEACa9RoKA48COtq1cCxcLhTR4HtWwvaLuIbthjudBGIAA1PeBvXhff77UHg7nQymIwa2tGiEm47mhnjcKthtA1Ed5AtRCo9WT86FQ26yY2Us33IKKyHe4wALIUQh6mGDuGsKacCi+-MAan1KtGnZX7jXA+nafEsAXR3YXHgO+nPFQyG4R0pGzPg4ZqPRnCnu7I4lIY5xk9piEWpyAA) - documentation https://esperanc.github.io/skulptIde/pages.html

Anderson's Brython tool: http://p5py.com/ also for reference.

For Pyodide mode I think it could be somewhat straightforward javascripting I suppose.

For Tanscrypt mode I wonder how far would we have to go (including in terms of infrastructure/server costs) to have some sort of site running pyp5j that could ingest code and spit a page with the JS....

**Comment by flavioamieiro** [comment]
That's really cool!

[Hydra does the same as another example](https://hydra.ojack.xyz/?code=JTBBb3NjKDQwJTJDJTIwMCklMEEucG9zdGVyaXplKCklMEEubW9kdWxhdGUob3NjKCgpJTIwJTNEJTNFJTIwTWF0aC5zaW4odGltZSklMjAqJTIwMykpJTBBLm91dCgp).

**Comment by villares** [comment]
@flavioamieiro, @eduardostalinho, would you like to try and hack something? My Javascript skills are poor..

My idea is like this:
(1) A JS function to encode the content of the current editor-widget at berinhard.github.io/pyp5js/pyodide/ as a URL safe string
(2) Another version of the berinhard.github.io/pyp5js/pyodide/ page that gets the code from the URL instead of the editor-widget
(3) A button on the current page that runs (1) and creates a sharable link to (2) adding the result of (1) to it.

**Comment by villares** [comment]
I asked @rodjuncode to have a look... 
but I'm not sure how it would integrate on the locally served worklow (it would be good in the context of the publicly served page)

**Comment by berinhard** [comment]
Honestly, I don't think adding behavior to the demo, the way the code is right now, is the way to go. I'm saying this because now the code base already counts with 3 places to integrate p5.js and python: transcrypt, pyodide and pyodide demo. Now that we have pyodide running within the project I really think that the demo should stand for what it is, a demo. 

Another think that leads me to think like that is the fact I don't think this repository should implement the best UX to use the project. I think about this repo the same way I think about Django: if I need to create python web applications, I use it as a dependency and not the source code of my web app. I think the same logic applies here.

**Comment by berinhard** [comment]
Just to be clear, I do think that this is an important and nice to have feature. But I'm not sure if pyp5js' repo and/or pyodide's demo is the best place to go with. Maybe it's better for us to focus on enabling people from extending pyp5js, instead of the project implementing everything.

For example, for this feature, if the user can add a custom JS file to the index.html or something like that, it should do the trick.

**Comment by villares** [comment]
Sure, don't bother with me... go on with your priorities. I totally understand.

For me, for teaching purposes, this is the kill feature, this would be much more useful to me than the local sketchbook (but I know the future of the project depends other core issues and the sketchboo), so I might try to get someone to help me with this on my fork.

**Comment by berinhard** [comment]
Opening this issue again after talking with @villares about how killer this feature can be =)

We can add a "Share this" button in the demo editor so the project can reach more people based on their natural engagement.

**Comment by villares** [comment]
For reference... snipets from amazing Prof. @esperanc's https://github.com/esperanc/skulptIde/tree/master/javascript

![image](https://user-images.githubusercontent.com/3694604/140002453-d2679afb-299f-4622-bf04-e450a7613ca4.png)

![image](https://user-images.githubusercontent.com/3694604/140002478-4175f3bc-6ada-408a-9262-0bb86495ba2c.png)

![image](https://user-images.githubusercontent.com/3694604/140002497-931e764f-5548-4180-8ac0-df77e9219de0.png)

**Comment by berinhard** [comment]
@jvfe I'm not trying to push more issues to you, but if you want to keep with your **STUNNING** contribution rate, this is a good candidate since it touches only the demo editor, where you've spent some time already.

**Comment by jvfe** [comment]
Definitely, I'll take a look at the examples given and try building something. From what I've seen, skulpt basically just encodes the sketch code in base64 and adds it as a URL param. Should be a simple starting point for me.

I'll draft a PR as soon as I have something to show.
