### ISSUE TITLE
disscussion/documentation of library ecossystems access

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#144]
I'd like to see somewhere (it could be on this issue or at the docs) some comments about where are we on the roadmap for using external libraries. This might seem very clear in the developers head but it seems unclear for me.

Which libs can be used already, what can be hacked in, what should have friendly support in the future?

Transcrypt mode:
-  We can use p5js DOM support out of the box.
-  How about other p5js geared libraries or other JS stuff?

Pyodide mode:
- Pyodide demos from Mozilla show off numpy, it makes the page download imense :(
- How will we enable Python libs?
- How will we enable JSp5js libs?

**Comment by berinhard** [comment]
### Transcrypt

> We can use p5js DOM support out of the box.

No because transcrypt's process forces us to "compile" all the libraries we want to use together. That's why you have to use `add_library` method as [shown here](https://berinhard.github.io/pyp5js/examples/sketch_008/index.html).

> How about other p5js geared libraries or other JS stuff?

Due to transcrypt's limitations and pyodide's simplifications, I tend have no interest on exploring this for now, but I don't think there's a way to implement this without making the same `add_library` method more powerful.

### Pyodide

Pyodide support was released in [0.5.1]() and is now pyp5js' default mode. This version focused on making sure pyp5js could run on top of multiple interpreters. A lot of progress was made in this direction, but there are still a few things to address to Pyodide. So, the next move is to focus in the pyodide working integration to improve it.

> Pyodide demos from Mozilla show off numpy, it makes the page download imense 

Totally agree and this is now documented in #148

> How will we enable Python libs?

I'm not sure for now, but I feel that the work required by #148 will help us to understand it better or even already do the job.

> How will we enable JSp5js libs?

Not sure as well, but this is already documented in the issue #150

To document my next goals to improve pyodide mode, I created [this milestone](https://github.com/berinhard/pyp5js/milestone/4) to group all the issues together and improve the work organization.

**Comment by villares** [comment]
> No because transcrypt's process forces us to "compile" all the libraries we want to use together. That's why you have to use `add_library` method as [shown here](https://berinhard.github.io/pyp5js/examples/sketch_008/index.html).
> 
> >

This is what I meant by "out of the box"! Just use` add_library` and you can use it (no downloads or extra installs).
