### ISSUE TITLE
fresh install issue on Linux

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#146]
Sorry to bear bad news, but a fresh install on a new machine, running `pyp5js serve` then the demo new sketch:

```
highlightjs.min.css:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
:5000/sketch/new_sketch/target/pyp5js.js:2263 
Uncaught SyntaxError: Unexpected token '==='
highlightjs.min.css:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```

![image](https://user-images.githubusercontent.com/3694604/105429300-e6c7bc80-5c2f-11eb-807f-7f74c6c17c05.png)

**Comment by berinhard** [comment]
@villares do you have more data on it? What distro are you using? Which pyp5js version you've installed? 

I recently installed pyp5js' [latest version (0.5.1)](https://pypi.org/project/pyp5js/) in a Ubuntu 20.04 notebook and it worked fine for both Pyodide and Transcrypt sketches.

Can you try to install the most up-to-date version and confirm if this problem is still happening? If not, can I close this issue?

**Comment by villares** [comment]
I have changed distro, from Xubuntu to Manjaro XFCE só I have to start all over. I'll will close this for now, and reopen if I have any trouble.
