### ISSUE TITLE
Support event functions on Pyodide mode

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#147]
Currently the event functions are not working for Pyodide. The strategy defined in [pyodide's `start_p5`](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/templates/pyodide/target_sketch.js.template#L1139) **does not work** because it is a copy from transcrypt's strategy.

Probably we can do it in a way less complicated manner for pyp5js

**Comment by villares** [comment]
I was trying some crude workarounds (because this seems crucial for me using pyp5js in class) like adding dummy empty functions for each event function and then trying assignment to _P5_INSTANCE.function_name (I know I would be still missing the globals injection) but I couldn't figure out when _P5_INSTANCE is available and when it's not (sometimes it worked, sometimes I've got a Name Error).

**Comment by berinhard** [comment]
@villares feel free to share any code samples you have from your attempts =S

**Comment by berinhard** [comment]
Target code: https://berinhard.github.io/pyp5js/examples/sketch_006/index.html
