### ISSUE TITLE
To serve assets + pyodide JS/CSS files locally

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#157]
We're using CDN versions for several JS/CSS dependencies such as [pyodide](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/templates/pyodide/index.html#L12) and [jquery](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/http/templates/view_sketch.html#L61).

We should use local dependencies instead to pyp5js web editor can still be usable when offline.

**Comment by jvfe** [comment]
Hi! I can probably work on this one.

But I wanted to ask if including JQuery as a project dependency is really necessary, since, from what I can see, it's only really being used [here in view_sketch.html](https://github.com/berinhard/pyp5js/blob/1ce3a4699f5a5d56567de25692566c39191ba2d5/pyp5js/http/templates/view_sketch.html#L87-L124), in some DOM manipulation that could easily be refactored to use just base javascript.

Just to test it, [I've removed JQuery code and CDN](https://github.com/jvfe/pyp5js/commit/2e08493af13b45eb7b60a3ae3be54759e0855a83) in [one of my branches](https://github.com/jvfe/pyp5js/tree/refactor/remove_jquery), if you'd like to test it, worked fine here.

I hope I'm not bothering you by asking this, it's just that I'm curious if it's some question of backwards compatibility or something like that.

But either way - jquery or not - I'd be glad to solve this issue, thanks!

**Comment by jvfe** [comment]
I completely agree with serving the other dependencies locally, it will greatly improve usability.

Just sent a PR: https://github.com/berinhard/pyp5js/pull/182 for what we discussed, thanks for the response!
