### ISSUE TITLE
Add support to p5.dom.js

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#16]
At this point, adding p5.dom.js to /static/ works, but I have to  use `_P5_INSTANCE.` to invoke the methods...

Could we leave a `P5` constant around for the moment to experiment with things?

Maybe this feature request could be more ambitious: 
To add smart infrastructure to support third-party JS libraries...

**Comment by berinhard** [comment]
Thanks for bringing this up! This would definitely be a good thing to work on :+1:

**Comment by berinhard** [comment]
This [stackoverflow topic](https://stackoverflow.com/questions/44473861/how-to-add-p5-dom-to-p5-js-in-instance-mode) is somehow related to this work.

**Comment by villares** [comment]
Hey @berinhard ! I finally made an example of `p5.dom.js` working with **pyp5js** :)
https://abav.lugaralgum.com/sketch-a-day/2019/sketch_190507a/index.html

**Comment by berinhard** [comment]
Thanks @villares! So it's simple, right? I mean, just by adding the js file to the `index.html` enabled the `p5.dom` API to be accessed via global `_P5_INSTANCE`. I'd like to hear yout thoughts about the command line interface to enable that. Do you think we should always add `p5.dom` or we should use a flag when creating the new sketch? Something like `pytop5js new sketch_name --with-p5.dom`?

I was always a strong fan of the `explicit is better the implicit` verse in the Zen of Python, so I tend to think the flag is the right path, but I know that on the other side, it complicates the usage for people non-familiar with the terminal interface.

While we don't have our amazing IDE to hide all these internals, I guess this will always be an open question for me...

**Comment by villares** [comment]
The most elegant solution, for me, would not involve the CLI, the user
would include:

`add('p5.dom.js')`

Or even `add('cdn...`

:)

**Comment by berinhard** [comment]
@villares what if we have a global variable named `dom`. Something like an already imported module... So we could call the methods like: 

```python
dom.createDiv()
dom.VIDEO
sound.sampleRate()
sound.bands
```

I guess we can assume that we'll always provide the `p5.dom.js` and `p5.sound.js` for now. What do you think?

**Comment by berinhard** [comment]
https://github.com/villares/sketch-a-day/tree/master/2019/sketch_190507a

**Comment by berinhard** [comment]
Maybe @lucianoratamero could help us with this `add` approach as well. I think it will require some js import or something like that...

**Comment by villares** [comment]
I think we are mixing many things here...

- Adding stuff to the index.html
-- should dom or sound be added by default? (perhaps no)
-- could we scan for mentions of dom or sound in order to add them?
-- add() syntax to add them?
-- magic comment to add them?  i.e. # include p5.dom.js (probably implemented by a pre-processor)

- global instance aliases and namespace issues
-- should we have a dom or sound global names? (I think yes)
-- should we have other global names like _P5_INSTANCE -> P5 (I don't no)

**Comment by berinhard** [comment]
@villares I'm a huge +1 for the `add_library("p5.dom")` in the beginning of the sketch. Something like:

```python
from pytop5js import *

add_library("p5.dom")

def setup():
    pass 

def draw():
    pass
.........
```

But this strategy bring us a challenge, and that's why I was tagging @lucianoratamero here. The thing is: this `add_library` function will never be executed as a python function, but as a JS one. This is because the `sketch.py` file never gets executed, but only "translated" to JS code. Because of that, this `add_library` will have to dynamically load the `p5.dom.js` file since it can't edit the `index.html` file. 

@lucianoratamero, I did some digging on that and got to [this stack overflow topic](https://stackoverflow.com/questions/5892845/how-to-load-one-javascript-file-from-another#5892894), but I'd like to hear your thoughts on that too.

@villares about the globals, we do already have a `p5` global variable holding all `p5` constants. So, I'm going to run some tests, but if `p5.js` already exposes a `p5.dom`, the API we desire is ready already =]

**Comment by villares** [comment]
A few questions to make us move forward on this issue:
- At what point is `index.html` built and by which script/routine?
- Could `monitor/transcript` commands trigger a rebuilding of `index.html`?

My guess is the `add_library(...` could be a dummy function (or maybe a test function that checks if the library is in place) serving as a token to be scanned on a Python pre-processing routine that then would add the library to he `index.html`.

**Comment by berinhard** [comment]
`index.html` is built by the `pyp5js new` command and I don't think that rebuilding the index would be ideal. Because, let's think about the following scenario:

1 - I ran `$ pyp5js new my_sketch` to create my new sketch;
2 - I updated my sketch by implementing `draw` and `setup`;
3 - I decided to customize my index by adding some HTML to it (some titles, headers, footers, whatever...)
4 - Then I thought "hm... it would be nice if people could play with my sketch's parameters";
5 - I add `add_library(...)` to my sketch and run the `transcrypt` command again;
6 - Oh, oh... my `index.html` was rebuilt and, by doing so, I lost *all* of my own HTML and CSS customization

I really think that the previous scenario is a reasonable one and that's why I think the extra modules, such as `p5.sound` and `p5.dom`, should be dynamically imported.

**Comment by villares** [comment]
I see dynamically importing is more elegant, but this is not what the other
P5.js editors do...

And I think I've seed warnings on one of them telling the .html was
automatically generated...

You could just change html near the original p5.js loading...

Devil's advocate :)

**Comment by berinhard** [comment]
Required work:

- [ ] Add all dom methods to yaml
- [ ] Add all dom variables to yaml
- [ ] Add all dom constants to yaml
- [ ] Update pytop5js.py
- [ ] Implement `add_library` function in `pytop5js.py` to inject the `script` tag
- [ ] Create an examples using the slider
- [ ] Add info on `add_library` to the readme

**Comment by berinhard** [comment]
Possible implementation for `add_library`:

![Screen Shot 2019-05-28 at 19 52 14](https://user-images.githubusercontent.com/238223/58763803-34148900-8536-11e9-9e29-1f7a080997ac.png)
