### ISSUE TITLE
Creating global variables inside functions doesn't work

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#17]
Or am I missing something?

```
from pytop5js import *

def setup():
    createCanvas(200, 200)
    global a
    a = 100

def draw():
    rect(a, 50, 50, 50)

# This is required by pyp5js to work
start_p5(setup, draw)
```

**Comment by berinhard** [comment]
I don't know if this is a real bug or a regular limitation from how transcrypt deals with globals variables. I'll try to make simpler proof of concept to check it.

**Comment by villares** [comment]
I have an idea for an ugly solution:
Scan code for the `global` keyword, parse the declared names and add them at the start of the code to be trancribed, each as a `name = None` line.

**Comment by berinhard** [comment]
**Maybe** this error can have something to do with how we're running the `transcrypt` command. From `$ transcrypt --help` I noticed this flag:

```
  -xg, --xglobs         allow use of the 'globals' function
```

We're not using it, so, maybe it can have something to do with this `globals` issues.

**Comment by berinhard** [comment]
More about how transcrypt [deals with globals](https://transcrypt.org/docs/html/supported_constructs.html?highlight=globals#global-variable-access-by-using-globals-variable-name)

**Comment by berinhard** [comment]
This is definitely an issue with Transcrypt and not pyp5js. I've created [an issue](https://github.com/QQuick/Transcrypt/issues/629) to document it and also to keep track of eventual updates on transcrypt dealing with global variables. But, for now, this issue will remain open as a "won't fix".

But, to use global variables, you'll have to "declare" them outside the functions. This is the same reason that forced me to do [this huge wall of `None` assignments](https://github.com/berinhard/pyp5js/blob/master/pyp5js/pytop5js.py#L743) in `pyp5js/pytop5js.py`. So, the fix for your example would be:

```python
from pytop5js import *

a = None
def setup():
    createCanvas(200, 200)
    global a
    a = 100

def draw():
    rect(a, 50, 50, 50)

# This is required by pyp5js to work
start_p5(setup, draw)
```

@villares maybe this is something we'd like to cover on the docs. Do you think we can relate this to the issue #23?

**Comment by villares** [comment]
Thanks! 

I don't like the sound of "won't fix" much, maybe I'm just not used to this terminology :)

I agree it should be a documented issue, something like a "known issue", on #23, sure!

**Comment by berinhard** [comment]
Closing this issue since we've listed the limitations [in the docs](https://berinhard.github.io/pyp5js/#known-issues-and-differences-to-the-processingpy-and-p5js-ways-of-doing-things)
