### ISSUE TITLE
Clear button doesn't properly stop the sketch and

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#198]
As the title describers, the sketch keeps on execution on the demo editor even if the user clears it. This is problematic because, after multiple executions, there's a considerable memory consumption by Pyodide. This also happens if the user clicks multiple times on the Run button. The result is that multiple p5 sketches are being created by the JS and they kept running, even though they aren't visible to the user. 

**To reproduce:**

1. After cloning the repo, goes to `docs/pyodide` directory and run a local server with `python -m http.server`
2. Access the demo editor locally at http://localhost:8000/
3. Update the draw function to also print the frame count (`print(frameCount)`);
4. Starts the sketch and then clear it;
5. You'll keep seeing prints with the current frame count of the invisible sketch;

The same can be achieved by clicking the run button again.

**How to fix**

For the **Clear** button, a [noLoop](https://p5js.org/reference/#/p5/noLoop) call **maybe** can do the tricky. For the multiple clicks on the run button, the existing [remove](https://p5js.org/reference/#/p5/remove) call should work, but for some reason it's not.

**Screen shot**

![Screenshot from 2021-11-02 19-30-50](https://user-images.githubusercontent.com/238223/139961247-2df43b9a-75f4-4b2a-add4-c246f0a34d72.png)

**Comment by jvfe** [comment]
Here's something I thought of that might work:

First, I believe the sketch is not stopping because the remove call is happening in the canvas object. If I change [this line in target_sketch.js](https://github.com/berinhard/pyp5js/blob/96a3f202a40df3795e4abd1fcee35652eee53cfa/docs/pyodide/target/target_sketch.js#L1677) to be:
`window.instance.remove()`

It should terminate the sketch loop completely. The same call could be made to the "Clear" button in [line 124 of index.html](https://github.com/berinhard/pyp5js/blob/96a3f202a40df3795e4abd1fcee35652eee53cfa/docs/pyodide/index.html#L124) instead of removing the text content on the sketch-holder element. 

I don't really know if this is the most optimal solution and if it even really works as expected, but it should help to give some indication as to how to solve this problem.

**Comment by berinhard** [comment]
Thanks for your comment @jvfe. I agree with you that the current `remove` call seems to be wrong because it's only clearing the canvas, not the sketch itself. I think what you're proposing is a valid path to explore.

**Comment by jvfe** [comment]
I tested the path I mentioned above and it seems to be working - [you can test it here](https://jvfe.github.io/pyp5js/pyodide/). Still don't know if it's the most optimal solution, but it works! hahah Sent a PR for it, in case you see it as useful.

**Comment by berinhard** [comment]
Yay! thanks for the easy way to debug this =)
